### PR TITLE
Web Layout 

### PR DESCRIPTION
**Pull request by HaseebAhmad23**

### CODE REVIEW

**Review by nguyenLisa — CHANGES_REQUESTED** [review]
Thanks for your work. Could you adjust the following:
- Make sure that the picture of the web browser is not pixellated. Here, it is. Best is if you use a vector image, or you re-create it using HTML elements.
- The websubcontainer element does not match the inner-rectangle of the background (see screenshot, where I have changed the background color of the websubcontainer to red). Please make sure that they match. In addition, the container should overflow:auto, to make sure that the contents do not overflow, and that scroll bars appear should it be the case.

Capture d’écran 2019-06-24 à 23 54 32

**Comment by HaseebAhmad23** [comment]
I have updated my code. Kindly review it and merge it.

**Comment by nguyenLisa** [comment]
Please resolve the conflicts first. Thanks.

**Comment by HaseebAhmad23** [comment]
Conflicts are resolved now.

**Review by nguyenLisa — APPROVED** [review]
LGTM

**Pull request merged**
